name: CI/CD Workflow with MariaDB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: system_pajak
        ports:
          - 3307:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Sesuaikan dengan versi PHP yang Anda gunakan
        extensions: mysqli, pdo_mysql
        coverage: none

    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    # Tambahkan langkah untuk menjalankan tes dan migrasi pada database lokal
    - name: Run Tests and Database Migrations
      run: |
        # Jalankan perintah untuk menguji aplikasi Anda
        # Jalankan perintah migrasi database
        # Contoh: php artisan migrate --database=mysql

    - name: Deploy to Production Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /path/to/your/webroot
          git pull origin main
          composer install --no-dev
          # Jalankan perintah untuk migrasi database di server produksi
          # Contoh: php artisan migrate --force
